proxy_location: EveryNode
http_options:
  host: 0.0.0.0
  port: 8000
grpc_options:
  port: 9000
  grpc_servicer_functions: []
logging_config:
  encoding: TEXT
  log_level: INFO
  logs_dir: null
  enable_access_log: true
applications:
- name: app1
  route_prefix: /
  import_path: service:boosting_model
  runtime_env:
    pip:
    - scikit-learn
  deployments:
  - name: BoostingModel
